### ISSUE TITLE
Support export file?

### ISSUE THREAD

**Issue by mark6969** [opencultureconsulting/openrefine-client#26]
Hello, I am using your project recently to design a program that can automatically generate processed files. I would like to ask if your project supports the function of exporting files? thinks

**Comment by felixlohmeier** [comment]
Hi @mark6969, I am glad that the tool is useful for you. What exactly do you mean by "exporting files"? In the README.md there are some examples mentioned for exporting OpenRefine projects.

Example command line tool:
```
--export --output=deduped.xls "duplicates".
```

Example Python library:
```
cli.export(p1.project_id, 'deduped.xls')
```

Does this help you already? Otherwise please ask again.

**Comment by mark6969** [comment]
Yes it work thank you
